const amulet = {
  implicit: ['18.5% Resistance to All Elements'],
  explicit: {
    generic: [
      'Control Impaired Duration Reduction',
      'Cooldown Reduction',
      'Critical Strike Chance Against Injured Enemies',
      'Crowd Control Duration',
      'Damage',
      'Damage for 4 seconds After Killing an Elite',
      'Damage Reduction',
      'Damage Reduction from Close Enemies',
      'Damage Reduction from Distance Enemies',
      'Damage Reduction while Injured',
      'Dexterity',
      'Dodge Chance',
      'Intelligence',
      'Movement Speed',
      'Movement Speed for 4 Seconds After Killing an Elite',
      'Shrine Buff Duration',
      'Slow Duration Reduction',
      'Socket',
      'Strength',
      'Thorns',
      'Total Armor',
      'Ultimate Skill Damage',
      'Willpower',
    ],
    barbarian: [
      'Brawling Skill Damage',
      'Damage Reduction from Enemies That Are Bleeding',
      'Damage Reduction while Fortified',
      'Damage with Dual-Wielded Weapons',
      'Damage with Skills that Swap to New Weapons',
      'Damage with Two-Handed Bludgeoning Weapons',
      'Damage with Two-Handed Slashing Weapons',
      'Fury Cost Reduction',
      'Overpower Damage with Two-Handed Bludgeoning Weapons',
      'Ranks of All Defensive Skills',
      'Ranks of All Weapon Mastery Skills',
      'Ranks of the Brute Force Passive',
      'Ranks of the Counteroffensive Passive',
      'Ranks of the Cut to the Bone Passive',
      'Ranks of the Heavy Handed Passive',
      'Ranks of the No Mercy Passive',
      'Ranks of the Outburst Passive',
      'Ranks of the Slaying Strike Passive',
      'Ranks of the Tough as Nails Passive',
      'Ranks of the Wallop Passive',
      'Weapon Mastery Skill Damage',
    ],
    druid: [
      'Companion Skill Damage',
      'Damage Reduction while Fortified',
      'Damage while in Human Form',
      'Damage while Shapeshifted',
      'Earth Skill Damage',
      'Overpower Damage with Werebear Skills',
      'Ranks of All Companion Skills',
      'Ranks of All Defensive Skills',
      'Ranks of All Wrath Skills',
      'Ranks of the Call of the Wild Passive',
      'Ranks of the Crushing Earth Passive',
      'Ranks of the Defiance Passive',
      'Ranks of the Envenom Passive',
      'Ranks of the Natural Disaster Passive',
      'Ranks of the Nature’s Reach Passive',
      'Ranks of the Quickshift Passive',
      'Ranks of the Resonance Passive',
      'Ranks of the Stone Guard Passive',
      'Ranks of the Toxic Claws Passive',
      'Ranks of the Wild Impulses Passive',
      'Spirit Cost Reduction',
      'Storm Skill Cooldown Reduction',
      'Storm Skill Damage',
      'Total Armor while in Werewolf Form',
      'Werebear Skill Damage',
      'Werewolf Skill Damage',
    ],
    necromancer: [
      'Blood Skill Damage',
      'Bone Skill Damage',
      'Damage Reduction from Affected By Shadow Damage Over Time Enemies',
      'Damage Reduction while Fortified',
      'Darkness Skill Damage',
      'Essence Cost Reduction',
      'Minion Attack Speed',
      'Ranks of All Corpse Skills',
      'Ranks of All Curse Skills',
      'Ranks of All Macabre Skills',
      'Ranks of the Amplify Damage Passive',
      'Ranks of the Coalesced Blood Passive',
      'Ranks of the Compound Fracture Passive',
      'Ranks of the Death’s Reach Passive',
      'Ranks of the Evulsion Passive',
      'Ranks of the Fueled by Death Passive',
      'Ranks of the Gloom Passive',
      'Ranks of the Hellbent Commander Passive',
      'Ranks of the Imperfectly Balanced Passive',
      'Ranks of the Terror Passive',
      'Ranks of the Tides of Blood Passive',
      'Summoning Skill Damage',
    ],
    rogue: [
      'Attack Speed for 4 seconds after Dodging an Attack',
      'Cutthroat Skill Damage',
      'Damage Reduction from Enemies That Are Poisoned',
      'Damage with Dual-Wielded Weapons',
      'Damage with Ranged Weapons',
      'Energy Cost Reduction',
      'Imbued Skill Damage',
      'Imbuement Skill Cooldown Reduction',
      'Marksman Skill Damage',
      'Rank of All Agility Skills',
      'Rank of All Imbuement Skills',
      'Ranks of All Subterfuge Skills',
      'Ranks of the Deadly Venom Passive',
      'Ranks of the Exploit Passive',
      'Ranks of the Frigid Finesse Passive',
      'Ranks of the Impetus Passive',
      'Ranks of the Malice Passive',
      'Ranks of the Weapon Mastery Passive',
      'Reduces the Arm Time of your Trap Skills',
      'Trap Skill Cooldown Reduction',
      'Trap Skill Damage',
    ],
    sorcerer: [
      'Conjuration Skill Damage',
      'Frost Skill Damage',
      'Lucky Hit Chance while You Have a Barrier',
      'Mana Cost Reduction',
      'Pyromancy Skill Damage',
      'Ranks of All Conjuration Skills',
      'Ranks of All Defensive Skills',
      'Ranks of All Mastery Skills',
      'Ranks of the Conjuration Mastery Passive',
      'Ranks of the Devouring Blaze Passive',
      'Ranks of the Elemental Dominance Passive',
      'Ranks of the Endless Pyre Passive',
      'Ranks of the Glass Cannon Passive',
      'Ranks of the Hoarfrost Passive',
      'Ranks of the Icy Touch Passive',
      'Ranks of the Inner Flames Passive',
      'Ranks of the Permafrost Passive',
      'Ranks of the Shocking Impact Passive',
      'Shock Skill Damage',
    ],
  },
  aspect: {
    generic: [],
    barbarian: [],
    druid: [],
    necromancer: [],
    rogue: [],
    sorcerer: [],
  },
};

export default amulet;
