const chest = {
  explicit: {
    generic: [
      'All Stats',
      'Cold Resistance',
      'Control Impaired Duration',
      'Damage',
      'Damage Reduction',
      'Damage Reduction from Close Enemies',
      'Damage Reduction from Distant Enemies',
      'Dexterity',
      'Fire Resistance',
      'Intelligence',
      'Life on Kill',
      'Lightning Resistance',
      'Maximum Life',
      'Poison Resistance',
      'Shadow Resistance',
      'Socket',
      'Strength',
      'Thorns',
      'Total Armor',
      'Ultimate Skill Damage',
      'Willpower',
    ],
    barbarian: [
      'Brawling Skill Damage',
      'Damage Reduction from Enemies That Are Bleeding',
      'Damage Reduction while Fortified',
      'Fortify Generation',
      'Physical Damage',
      'Ranks of Challenging Shout',
      'Ranks of Ground Stomp',
      'Ranks of Iron Skin',
      'Ranks of Rallying Cry',
      'Weapon Mastery Skill Damage',
    ],
    druid: [
      'Companion Skill Damage',
      'Damage Reduction from Enemies That Are Poisoned',
      'Damage Reduction while Fortified',
      'Damage while in Human Form',
      'Damage while Shapeshifted',
      'Earth Skill Damage',
      'Fortify Generation',
      'Lightning Damage',
      'Overpower Damage with Werebear Skills',
      'Physical Damage',
      'Poison Damage',
      'Ranks of Blood Howl',
      'Ranks of Cyclone Armor',
      'Ranks of Debilitating Roar',
      'Ranks of Earthen Bulwark',
      'Storm Skill Damage',
      'Werebear Skill Damage',
      'Werewolf Skill Damage',
    ],
    necromancer: [
      'Blood Skill Damage',
      'Bone Skill Damage',
      'Damage for 4 Seconds After Picking Up a Blood Orb',
      'Damage Reduction from Affected By Shadow Damage Over Time Enemies',
      'Damage Reduction while Fortified',
      'Darkness Skill Damage',
      'Fortify Generation',
      'Maximum Minion Life',
      'Physical Damage',
      'Shadow Damage',
      'Summoning Skill Damage',
    ],
    rogue: [
      'Cutthroat Skill Damage',
      'Damage Reduction from Enemies That Are Poisoned',
      'Damage with Dual-Wielded Weapons',
      'Damage with Ranged Weapons',
      'Damage with Skills that Swap to New Weapons',
      'Imbued Skill Damage',
      'Marksman Skill Damage',
      'Physical Damage',
      'Poison Damage',
      'Shadow Damage',
      'Trap Skill Damage',
    ],
    sorcerer: [
      'Barrier Generation',
      'Cold Damage',
      'Conjuration Skill Damage',
      'Damage Reduction from Enemies That Are Burning',
      'Fire Damage',
      'Frost Skill Damage',
      'Lightning Damage',
      'Pyromancy Skill Damage',
      'Shock Skill Damage',
    ],
  },
  aspect: {
    generic: [],
    barbarian: [],
    druid: [],
    necromancer: [],
    rogue: [],
    sorcerer: [],
  },
};

export default chest;
