const gloves = {
  explicit: {
    generic: [
      'All Stats',
      'Attack Speed',
      'Critical Strike Chance',
      'Critical Strike Chance Against Injured Enemies',
      'Damage to Injured Enemies',
      'Dexterity',
      'Intelligence',
      'Lucky Hit Chance',
      'Lucky Hit: Chance to Restore [X]% Primary Resource',
      'Lucky Hit: Up to a [X]% Chance to Heal',
      'Lucky Hit: Up to a [X]% Chance to Slow',
      'Overpower Damage',
      'Strength',
      'Willpower',
    ],
    barbarian: [
      'Physical Damage Over Time',
      'Ranks of Double Swing',
      'Ranks of Hammer of the Ancients',
      'Ranks of Rend',
      'Ranks of Upheaval',
      'Ranks of Whirlwind',
    ],
    druid: [
      'Critical Strike Damage with Earth Skills',
      'Critical Strike Damage with Werewolf Skills',
      'Ranks of Landslide',
      'Ranks of Lightning Storm',
      'Ranks of Pulverize',
      'Ranks of Shred',
      'Ranks of Tornado',
      'Storm Skill Cooldown Reduction',
    ],
    necromancer: [
      'Critical Strike Damage with Bone Skills',
      'Ranks of Blight',
      'Ranks of Blood Lance',
      'Ranks of Blood Surge',
      'Ranks of Bone Spear',
      'Ranks of Sever',
      'Shadow Damage Over Time',
    ],
    rogue: [
      'Attack Speed for 4 seconds after Dodging an Attack',
      'Critical Strike Damage with Imbued Skills',
      'Ranks of Barrage',
      'Ranks of Flurry',
      'Ranks of Penetrating Shot',
      'Ranks of Rapid Fire',
      'Ranks of Twisting Blades',
      'Reduces the Arm Time of your Trap Skills',
      'Trap Skill Cooldown Reduction',
    ],
    sorcerer: [
      'Fire Damage Over Time',
      'Lightning Critical Strike Damage',
      'Ranks of Chain Lightning',
      'Ranks of Charged Bolts',
      'Ranks of Fireball',
      'Ranks of Frozen Orb',
      'Ranks of Ice Shards',
      'Ranks of Incinerate',
    ],
  },
  aspect: {
    generic: [],
    barbarian: [],
    druid: [],
    necromancer: [],
    rogue: [],
    sorcerer: [],
  },
};

export default gloves;
