const helm = {
  explicit: {
    generic: [
      'All Stats',
      'Basic Skill Attack Speed',
      'Cold Resistance',
      'Cooldown Reduction',
      'Crowd Control Duration',
      'Dexterity',
      'Fire Resistance',
      'Healing Received',
      'Intelligence',
      'Life On Kill',
      'Life Regeneration while Not Damaged Recently',
      'Lightning Resistance',
      'Maximum Life',
      'Poison Resistance',
      'Shadow Resistance',
      'Socket',
      'Strength',
      'Total Armor',
      'Willpower',
    ],
    barbarian: ['Maximum Fury', 'Ranks of Death Blow', 'Ranks of Rupture', 'Ranks of Steel Grasp'],
    druid: ['Maximum Spirit', 'Ranks of Poison Creeper', 'Ranks of Ravens', 'Ranks of Wolves'],
    necromancer: ['Maximum Essence', 'Ranks of Decrepify', 'Ranks of Iron Maiden'],
    rogue: [
      'Damage with Dual-Wielded Weapons',
      'Maximum Energy',
      'Ranks of Cold Imbuement',
      'Ranks of Poison Imbuement',
      'Ranks of Shadow Imbuement',
    ],
    sorcerer: [
      'Barrier Generation',
      'Lucky Hit Chance while You Have a Barrier',
      'Maximum Mana',
      'Ranks of Hydra',
      'Ranks of Ice Blades',
      'Ranks of Lightning Spear',
    ],
  },
  aspect: {
    generic: [],
    barbarian: [],
    druid: [],
    necromancer: [],
    rogue: [],
    sorcerer: [],
  },
};

export default helm;
