const offHands = {
  implicit: ['7% Cooldown Reduction'],
  explicit: {
    generic: [
      'All Stats',
      'Basic Skill Attack Speed',
      'Basic Skill Damage',
      'Cooldown Reduction',
      'Critical Strike Chance',
      'Critical Strike Chance Against Injured Enemies',
      'Crowd Control Duration',
      'Dexterity',
      'Healing Received',
      'Intelligence',
      'Life On Kill',
      'Lucky Hit Chance',
      'Lucky Hit: Chance to Restore [X]% Primary Resource',
      'Lucky Hit: Up to [X]% Chance to Slow',
      'Lucky Hit: Up to a [X]% Chance to Heal',
      'Resource Generation',
      'Socket',
      'Strength',
      'Willpower',
    ],
    druid: [
      'Damage Reduction from Enemies That Are Poisoned',
      'Damage Reduction while Fortified',
      'Fortify Generation',
      'Spirit Cost Reduction',
    ],
    necromancer: [
      'Blood Orb Healing',
      'Damage Reduction from Affected By Shadow Damage Over Time Enemies',
      'Damage Reduction while Fortified',
      'Essence Cost Reduction',
      'Fortify Generation',
      'Maximum Minion Life',
    ],
    sorcerer: [
      'Barrier Generation',
      'Crackling Energy Damage',
      'Damage Reduction from Enemies That Are Burning',
      'Lucky Hit Chance while You Have a Barrier',
      'Mana Cost Reduction',
    ],
  },
  aspect: {
    generic: [],
    barbarian: [],
    druid: [],
    necromancer: [],
    rogue: [],
    sorcerer: [],
  },
};

export default offHands;
