const pants = {
  implicit: [
    'While Injured, Your Potion Also Grants X% Maximum Life as Barrier',
    'While Injured, Your Potion Also Grants X% Movement Speed for 2 Seconds',
    'While Injured, Your Potion Also Restores X% Resource',
  ],
  explicit: {
    generic: [
      'All Stats',
      'Damage for 4 seconds After Killing an Elite',
      'Damage Reduction',
      'Damage Reduction from Close Enemies',
      'Damage Reduction from Distant Enemies',
      'Dexterity',
      'Dodge Chance',
      'Dodge Chance Against Close Enemies',
      'Healing Received',
      'Intelligence',
      'Life Regeneration while Not Damaged Recently',
      'Maximum Life',
      'Potion Capacity',
      'Potion Drop Rate',
      'Socket',
      'Strength',
      'Thorns',
      'Total Armor',
      'Willpower',
    ],
    barbarian: [
      'Berserking Duration',
      'Damage Reduction from Enemies That Are Bleeding',
      'Damage Reduction while Fortified',
      'Ranks of Charge',
      'Ranks of Kick',
      'Ranks of Leap',
      'Ranks of War Cry',
    ],
    druid: [
      'Damage Reduction from Enemies that are Poisoned',
      'Damage Reduction while Fortified',
      'Ranks of Boulder',
      'Ranks of Hurricane',
      'Ranks of Rabies',
      'Ranks of Trample',
      'Total Armor while in Werebear Form',
    ],
    necromancer: [
      'Damage Reduction from Affected By Shadow Damage Over Time Enemies',
      'Damage Reduction while Fortified',
      'Ranks of Blood Mist',
      'Ranks of Bone Prison',
      'Ranks of Corpse Explosion',
    ],
    rogue: [
      'Damage for 4 Seconds After Dodging an Attack',
      'Damage Reduction from Enemies that are Poisoned',
      'Imbuement Skill Cooldown',
      'Ranks of Concealment',
      'Ranks of Dark Shroud',
      'Ranks of Poison Trap',
      'Ranks of Smoke Grenade',
    ],
    sorcerer: [
      'Crackling Energy Damage',
      'Damage Reduction from Enemies That Are Burning',
      'Ranks of Ball Lightning',
      'Ranks of Blizzard',
      'Ranks of Firewall',
      'Ranks of Meteor',
    ],
  },
  aspect: {
    // generic: [
    //   'You gain [0.25 - 0.50%] increased Armor for 4 seconds when you deal any form of damage, stacking up to [25.00 - 50.00%]',
    //   'Basic Skills grant 20% Damage Reduction for [2.0 - 6.0] seconds',
    //   'You Heal for [X] Life per second for each Close enemy, up to [X] Life per second',
    //   'While you have a Barrier active, there is a [7 - 13%] chance to ignore incoming direct damage from Distant enemies',
    //   'Damaging an Elite enemy grants you a Barrier absorbing up to [X] damage for 10 seconds. This effect can only happen once every 30 seconds',
    //   'When hit while not Healthy, a magical bubble is summoned around you for [3 - 5] seconds. While standing in the bubble players are Immune. Can only occur once every 90 seconds',
    // ],
    barbarian: [
      // 'Leap creates an Earthquake that deals [X] Physical damage over 4 seconds. While standing in Earthquakes, you gain [5 - 15%] increased Damage Reduction',
      'Each point of Fury generated while at Maximum Fury grants [X] Fortify',
      // 'After swapping weapons 6 times, gain [X] Fortify',
      // 'Iron Skin grants Unstoppable, and [10 - 20%] Damage Reduction',
      // 'Gain [2.0 - 4.0%] Damage Reduction for each Nearby Bleeding enemy up to [10 - 20%] maximum',
      // 'Lucky Hit: Up to a 35% chance to gain [X] Fortify whenever you deal direct damage while Berserking',
    ],
    druid: [],
    necromancer: [],
    rogue: [],
    sorcerer: [],
  },
};

export default pants;
