const shield = {
  implicit: ['20% Block Chance', '60% Block Damage Reduction', '627 Thorns', '80% Main Hand Weapon Damage'],
  explicit: {
    generic: [
      'All Stats',
      'Basic Skill Attack Speed',
      'Basic Skill Damage',
      'Cooldown Reduction',
      'Critical Strike Chance',
      'Critical Strike Chance Against Injured Enemies',
      'Crowd Control Duration',
      'Damage Reduction',
      'Damage Reduction from Close Enemies',
      'Damage Reduction from Distant Enemies',
      'Dexterity',
      'Healing Received',
      'Intelligence',
      'Life On Kill',
      'Lucky Hit Chance',
      'Lucky Hit: Chance to Restore [X]% Primary Resource',
      'Lucky Hit: Up to [X]% Chance to Slow',
      'Lucky Hit: Up to a [X]% Chance to Heal',
      'Maximum Life',
      'Resource Generation',
      'Socket',
      'Strength',
      'Thorns',
      'Willpower',
    ],
    necromancer: [
      'Blood Orb Healing',
      'Damage for 4 Seconds After Picking Up a Blood Orb',
      'Damage Reduction from Affected By Shadow Damage Over Time Enemies',
      'Damage Reduction while Fortified',
      'Essence Cost Reduction',
      'Fortify Generation',
      'Maximum Minion Life',
      'Minion Attack Speed',
    ],
  },
  aspect: {
    generic: [],
    barbarian: [],
    druid: [],
    necromancer: [],
    rogue: [],
    sorcerer: [],
  },
};

export default shield;
