const weapon = {
  implicit: [
    '1h Axe 28% Damage to Healthy Enemies',
    '1h Mace 31.5% Overpower Damage',
    '1h Scythe 206 Life on Kill',
    '1h Sword 17.5% Critical Strike Damage',
    '2h Axe 56% Damage to Healthy Enemies',
    '2h Mace 63% Overpower Damage',
    '2h Scythe 411 Life on Kill',
    '2h Sword 35% Critical Strike Damage',
    'Bow 40% Damage to Distant Enemies',
    'Crossbow 40% Vulnerable Damage',
    'Dagger 20% Damage to Close Enemies',
    'Polearm 56% Damage to Injured Enemies',
    'Staff 35% Damage to Crowd Controlled Enemies',
    'Wand 10% Lucky Hit Chance',
  ],
  explicit: {
    generic: [
      'All Stats',
      'Basic Skill Damage',
      'Core Skill Damage',
      'Critical Strike Damage',
      'Damage Over Time',
      'Damage to Close Enemies',
      'Damage to Crowd Controlled Enemies',
      'Damage to Distant Enemies',
      'Damage to Injured Enemies',
      'Damage to Slowed Enemies',
      'Damage to Stunned Enemies',
      'Lucky Hit: Up to [X] Chance to Execute Injured Non-Elites',
      'Overpower Damage',
      'Socket',
      'Ultimate Skill Damage',
      'Vulnerable Damage',
    ],
    barbarian: ['Damage to Bleeding Enemies', 'Damage while Berserking', 'Strength'],
    druid: [
      'Critical Strike Damage with Earth Skills',
      'Critical Strike Damage with Werewolf Skills',
      'Damage to Poisoned Enemies',
      'Lightning Critical Strike Damage',
      'Overpower Damage with Werebear Skills',
      'Willpower',
    ],
    necromancer: [
      'Critical Strike Damage with Bone Skills',
      'Damage to Affected by Shadow Damage Over Time Enemies',
      'Intelligence',
    ],
    rogue: [
      'Critical Strike Damage with Imbued Skills',
      'Damage to Chilled Enemies',
      'Damage to Dazed Enemies',
      'Damage to Enemies Affected by Trap Skills',
      'Damage to Frozen Enemies',
      'Damage to Poisoned Enemies',
      'Dexterity',
    ],
    sorcerer: [
      'Damage to Burning Enemies',
      'Damage to Chilled Enemies',
      'Damage to Frozen Enemies',
      'Intelligence',
      'Lightning Critical Strike Damage',
    ],
  },
  aspect: {
    generic: [],
    barbarian: [],
    druid: [],
    necromancer: [],
    rogue: [],
    sorcerer: [],
  },
};

export default weapon;
